-
  name: 山田開斗
  affiliation: 宮下研
  twitter: ""
-
  name: できゅうさん（ア口ーラのすがた）
  affiliation: 宮下研OB
  twitter: '@de_kyuu'
-
  name: 簗瀬洋平
  affiliation: 'Unity Technologies Japan'
  twitter: '@yoh7686'
-
  name: matatsuna
  affiliation: '明治大学 中村研究室'
  twitter: '@matatsuna'
-
  name: 上野新葉
  affiliation: 宮下研
  twitter: '@saraha_fms'
-
  name: 中村建斗
  affiliation: '明治大学 阿原研究室'
  twitter: ""
-
  name: '湯村 翼'
  affiliation: '国立研究開発法人 情報通信研究機構'
  twitter: '@yumu19'
-
  name: '岩淵 勇樹'
  affiliation: 面白法人カヤック
  twitter: '@butchi_y'
-
  name: ひろえってぃ
  affiliation: 小林研
  twitter: '@hiroetty_fms'
-
  name: しょーやくん
  affiliation: 宮下研究室
  twitter: '@tkd_meiji'
-
  name: 'まつお （0.0 / 5.0 km）'
  affiliation: 宮下研M1
  twitter: ""
-
  name: 大場直史
  affiliation: 宮下研究室
  twitter: '@frog_aboon'
-
  name: 3846masa
  affiliation: '明治大学 宮下研究室'
  twitter: '@3846masa'
