isTest: false
title: ABPro 2016
description: >
  人を驚かせ，笑わせ，幸せにするような「普通じゃないプログラム作品」発表会！
  2016年9月24日 明治大学 中野キャンパスにて！
twitterID: @miyashita_lab
registerUrl: https://goo.gl/forms/s0sx9oyRx1PFmKKp2
members:
  - 宮代 理弘
  - 山中 祥太
  - 加藤 邦拓
  - 高橋 治輝
  - 若林 裕太
  - 秋山 耀
  - 松尾 良馬
  - 薄羽 大樹
  - 大場 直史
  - 小川 優
  - 小林 岳
  - 下野 弘朗
  - 高井 菜々子
  - 高田 勝也
  - 高橋 弘毅
  - 土井 麻由佳
  - 鳥山 らいか
  - 林 初実
  - 上野 新葉
  - 岡田 直観
  - 小渕 豊
  - 金杉 季実果
  - 戸田 大貴
  - 迎 崇久
  - 山田 開斗
  - 木崎 駿也
  - 島田 雄輝
  - 宮坂 和樹
  - 小林 巧
  - 塩出 研史
  - 田口 諒
